default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: Root@123
  host: localhost

development:
  <<: *default
  database: lending_app_development

test:
  <<: *default
  database: lending_app_test

production:
  <<: *default
  database: lending_app_production
